/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   urls.go                                            :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: lpaulo-m <lpaulo-m@student.42sp.org.br>    +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2021/04/22 20:47:39 by lpaulo-m          #+#    #+#             */
/*   Updated: 2021/04/22 20:50:26 by lpaulo-m         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

package main

// [...] declares a fixed-size array
var demoUrls = []string{
	"https://nomadcoders.co",
	"https://golang.org",
	"https://www.youtube.com",
	"https://github.com/librity",
	"https://profile.intra.42.fr",
	"https://rocketseat.com.br",
	"https://egghead.io",
	"https://duckduckgo.com",
	"https://elixirschool.com",
	"https://www.amazon.com",
	"https://www.airbnb.com",
	"https://www.soundcloud.com",
	"https://www.facebook.com",
	"https://www.instagram.com",
	"https://www.spotify.com/br/home",
}

// 100 most visited sites (https://ahrefs.com/blog/most-visited-websites/)
var stressUrls = []string{
	"https://www.en.wikipedia.org",
	"https://www.youtube.com",
	"https://www.amazon.com",
	"https://www.facebook.com",
	"https://www.twitter.com",
	"https://www.fandom.com",
	"https://www.pinterest.com",
	"https://www.imdb.com",
	"https://www.reddit.com",
	"https://www.yelp.com",
	"https://www.instagram.com",
	"https://www.ebay.com",
	"https://www.walmart.com",
	"https://www.craigslist.org",
	"https://www.healthline.com",
	"https://www.tripadvisor.com",
	"https://www.linkedin.com",
	"https://www.webmd.com",
	"https://www.netflix.com",
	"https://www.apple.com",
	"https://www.homedepot.com",
	"https://www.mail.yahoo.com",
	"https://www.cnn.com",
	"https://www.etsy.com",
	"https://www.google.com",
	"https://www.yahoo.com",
	"https://www.indeed.com",
	"https://www.target.com",
	"https://www.microsoft.com",
	"https://www.nytimes.com",
	"https://www.mayoclinic.org",
	"https://www.espn.com",
	"https://www.usps.com",
	"https://www.quizlet.com",
	"https://www.gamepedia.com",
	"https://www.lowes.com",
	"https://www.irs.gov",
	"https://www.nih.gov",
	"https://www.merriam-webster.com",
	"https://www.steampowered.com",
	"https://www.mapquest.com",
	"https://www.foxnews.com",
	"https://www.allrecipes.com",
	"https://www.quora.com",
	"https://www.aol.com",
	"https://www.britannica.com",
	"https://www.live.com",
	"https://www.bestbuy.com",
	"https://www.rottentomatoes.com",
	"https://www.ca.gov",
	"https://www.play.google.com",
	"https://www.cnet.com",
	"https://www.roblox.com",
	"https://www.usnews.com",
	"https://www.zillow.com",
	"http://www.businessinsider.com",
	"http://www.bulbagarden.net",
	"http://www.paypal.com",
	"http://www.finance.yahoo.com",
	"http://www.genius.com",
	"http://www.usatoday.com",
	"http://www.realtor.com",
	"http://www.medicalnewstoday.com",
	"http://www.fedex.com",
	"http://www.bankofamerica.com",
	"http://www.washingtonpost.com",
	"http://www.investopedia.com",
	"http://www.speedtest.net",
	"http://www.spotify.com",
	"http://www.cdc.gov",
	"http://www.chase.com",
	"http://www.hulu.com",
	"http://www.xfinity.com",
	"http://www.msn.com",
	"http://www.dictionary.com",
	"http://www.weather.com",
	"http://www.ups.com",
	"http://www.verizon.com",
	"http://www.forbes.com",
	"http://www.wowhead.com",
	"http://www.expedia.com",
	"http://www.urbandictionary.com",
	"http://www.foodnetwork.com",
	"http://www.nbcnews.com",
	"http://www.macys.com",
	"http://www.apartments.com",
	"http://www.ign.com",
	"http://www.capitalone.com",
	"http://www.costco.com",
	"http://www.theguardian.com",
	"http://www.cnbc.com",
	"http://www.glassdoor.com",
	"http://www.yellowpages.com",
	"http://www.att.com",
	"http://www.bbc.com",
	"http://www.khanacademy.org",
	"http://www.ny.gov",
	"http://www.twitch.tv",
	"http://www.adobe.com",
	"http://www.cbssports.com",
}
